# Site settings
title: OggCamp 2018 Repository
name: Mike Hingley
email: computa_mike@hotmail.com
baseurl: "/oggcamp-2018"
url: "https://computamike.github.io/oggcamp-2018/"
description: This is the OggCamp 2018 repository.
twitter_username: computa_mike
github_username: computa_mike
author: Mike Hingley
# Build settings
# markdown: kramdown
# permalink: /:year/:month/:title/
# sass:
#   style: compressed
# plugins:
#   - jekyll-sitemap
#   - jekyll-redirect-from
#   - jekyll-gist
exclude:
  - README.md


theme: jekyll-theme-midnight
