# Site settings
title: OggCamp 2018 Repository
name: Mike Hingley
email: computa_mike@hotmail.com
baseurl: "/oggcamp-2018"
url: "https://computamike.github.io/oggcamp-2018/"
description: This is the OggCamp 2018 repository.
twitter_username: computa_mike
github_username: computa_mike
author: Mike Hingley
# Build settings
# markdown: kramdown
# permalink: /:year/:month/:title/
# sass:
#   style: compressed
# plugins:
#   - jekyll-sitemap
#   - jekyll-redirect-from
#   - jekyll-gist
exclude:
  - README.md
  - reveal.js/index.html
  - reveal.js/plugin/markdown/example.html
  - reveal.js/plugin/notes/notes.html
  - reveal.js/plugin/notes-server/notes.html
  - reveal.js/test/
  - reveal.js/*.md
  - reveal.js/Gruntfile.js
  - reveal.js/package.json
  - reveal.js/LICENSE

theme: jekyll-theme-midnight
